/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_camera_live_RtmpClient */

#ifndef _Included_com_wind_ndk_camera_live_RtmpClient
#define _Included_com_wind_ndk_camera_live_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_camera_live_RtmpClient
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_camera_live_RtmpClient_nativeInit
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_camera_live_RtmpClient
 * Method:    native_initVideoEnc
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_camera_live_RtmpClient_native_1initVideoEnc
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_wind_ndk_camera_live_RtmpClient
 * Method:    native_connect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_camera_live_RtmpClient_native_1connect
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
