/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_camera_live_ImageUtil */

#ifndef _Included_com_wind_ndk_camera_live_ImageUtil
#define _Included_com_wind_ndk_camera_live_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_camera_live_ImageUtil
 * Method:    i420Rotate
 * Signature: ([BIII)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_camera_live_ImageUtil_i420Rotate
  (JNIEnv *, jclass, jbyteArray, jbyteArray,jint, jint, jint);

/*
 * Class:     com_wind_ndk_camera_live_ImageUtil
 * Method:    scale
 * Signature: ([B[BIIII)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_camera_live_ImageUtil_i420Scale
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
